Repository liveblocks/liveblocks, pull requests merged in 2024-02, with the labels that each got.

#1464 Tiny test tweak
  packages/liveblocks-core/src/__tests__/auth-manager.test.ts
Labels: small

#1474 Docs: Update webhooks videos to include new events
  assets/webhooks/create-endpoint.mp4
  assets/webhooks/edit-events.mp4
  docs/pages/platform/webhooks.mdx
  docs/pages/products/comments/email-notifications.mdx
Labels: documentation

#1483 Fix UI bug in Monaco example
  examples/nextjs-yjs-monaco/src/components/Cursors.tsx
Labels: bug, small

#1487 Don't return anything in Next auth endpoint handlers
  examples/nextjs-form/pages/api/liveblocks-auth.ts
  examples/nextjs-live-avatars-advanced/pages/api/liveblocks-auth.ts
  examples/nextjs-live-avatars/pages/api/liveblocks-auth.ts
  examples/nextjs-live-cursors-advanced/pages/api/liveblocks-auth.ts
  examples/nextjs-nextauth-google-avatars/pages/api/liveblocks-auth.ts
  examples/nextjs-spreadsheet-advanced/src/pages/api/liveblocks-auth.ts
  examples/nextjs-whiteboard-advanced/pages/api/liveblocks-auth.ts
Labels: small
